export const BRAND = Object.freeze({
  name: "Neopian Assistant",
  storeTitle: "Neopian Assistant — Dailies, Pricing & Shop Tools",
  tagline: "Your all-in-one companion for smarter Neopets routines.",
  disclaimer:
    "Neopian Assistant is an unofficial fan-made extension and is not affiliated with, endorsed by, or sponsored by Neopets.",
});

export const APP_VERSION = "7.13.0";
export const SCHEMA_VERSION = 6;

export const STORAGE_KEYS = Object.freeze({
  data: "neopianAssistant.data",
  operationHistory: "neopianAssistant.operationHistory",
  purchaseHistory: "neopianAssistant.purchaseHistory",
  mainShopHistory: "neopianAssistant.mainShopHistory",
  migrationComplete: "neopianAssistant.migrationComplete",
});

export const LEGACY_STORAGE_KEYS = Object.freeze({
  data: "jt_dailies_os_data_v75_pro",
  lastResetDate: "jt_dailies_os_last_nst_v75",
});

export const MESSAGE_TYPES = Object.freeze({
  openOptions: "extension.openOptions",
  lookupPrice: "shop.lookupPrice",
  cancelPriceRun: "shop.cancelPriceRun",
  preparePriceApply: "shop.preparePriceApply",
  confirmPriceApply: "shop.confirmPriceApply",
  applyPrices: "shop.applyPrices",
  recordVerification: "shop.recordVerification",
  authorizePurchaseLookup: "shop.authorizePurchaseLookup",
  cancelPurchaseMonitor: "shop.cancelPurchaseMonitor",
  preparePurchase: "shop.preparePurchase",
  authorizePurchaseRecheck: "shop.authorizePurchaseRecheck",
  bindPurchaseReview: "shop.bindPurchaseReview",
  confirmPurchase: "shop.confirmPurchase",
  purchaseItem: "shop.purchaseItem",
  recordPurchaseVerification: "shop.recordPurchaseVerification",
  authorizeMainShopLookup: "mainShop.authorizeLookup",
  cancelMainShopMonitor: "mainShop.cancelMonitor",
  prepareMainShopPurchase: "mainShop.preparePurchase",
  confirmMainShopPurchase: "mainShop.confirmPurchase",
  getMainShopPurchase: "mainShop.getPurchase",
  advanceMainShopPurchase: "mainShop.advancePurchase",
  completeMainShopPurchase: "mainShop.completePurchase",
});

export const SHOP_LIMITS = Object.freeze({
  maxItemIdLength: 16,
  maxItemNameLength: 100,
  maxItemsPerRun: 25,
  maxPurchaseWatchlistItems: 10,
  maxShopRows: 100,
  maxPrice: 999_999,
  minLookupIntervalMs: 6_000,
  maxLookupIntervalMs: 60_000,
  requestTimeoutMs: 15_000,
  applyTimeoutMs: 20_000,
  lockTtlMs: 45_000,
  confirmationTtlMs: 30_000,
  freshReviewTtlMs: 30_000,
  maxResponseBytes: 2_000_000,
});

export const PURCHASE_LIMITS = Object.freeze({
  defaultMaximumPrice: 1_000,
  absoluteMaximumPrice: 999_999,
  confirmationTtlMs: 30_000,
  freshLookupAttempts: 8,
  reviewTtlMs: 3 * 60_000,
  lockTtlMs: 45_000,
  deduplicationWindowMs: 24 * 60 * 60 * 1000,
  requestTimeoutMs: 20_000,
});

export const MAIN_SHOP_LIMITS = Object.freeze({
  shopId: 2,
  maxWatchlistItems: 100,
  minLookupIntervalMs: 8_000,
  maxLookupIntervalMs: 60_000,
  requestTimeoutMs: 15_000,
  reviewTtlMs: 30_000,
  purchaseTtlMs: 10 * 60_000,
  verificationTimeoutMs: 5 * 60_000,
  lockTtlMs: 10 * 60_000,
  deduplicationWindowMs: 24 * 60 * 60 * 1000,
});

export const DEFAULT_SETTINGS = Object.freeze({
  enabled: true,
  theme: "system",
  density: "comfortable",
  panel: {
    top: 20,
    right: 20,
    width: 390,
    minimized: false,
  },
  dailiesEnabled: true,
  autoPricing: {
    enabled: false,
    dryRun: true,
    rule: "undercut",
    amount: 1,
    floor: 1,
    maxItems: 10,
    requestIntervalMs: 8_000,
  },
  autoBuy: {
    enabled: false,
    dryRun: true,
    maximumPrice: PURCHASE_LIMITS.defaultMaximumPrice,
    watchlist: [],
    requestIntervalMs: 8_000,
  },
  mainShopBuy: {
    enabled: false,
    dryRun: true,
    watchlist: [],
    requestIntervalMs: 10_000,
  },
  privacyAcknowledged: false,
});

export const DEFAULT_DAILIES = Object.freeze([
  {
    id: "daily-advent-calendar",
    name: "Advent Calendar",
    url: "https://www.neopets.com/winter/adventcalendar.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day during December",
    iconUrl: "https://images.neopets.com/items/fur_mistletoe_wreath.gif",
  },
  {
    id: "daily-anchor-management",
    name: "Anchor Management",
    url: "https://www.neopets.com/pirates/anchormanagement.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/fur_pirate_anchor.gif",
  },
  {
    id: "daily-apple-bobbing",
    name: "Apple Bobbing",
    url: "https://www.neopets.com/halloween/applebobbing.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/spf_slimy_apple.gif",
  },
  {
    id: "daily-bank-interest",
    name: "Bank Interest",
    url: "https://www.neopets.com/bank.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/ltoo_scorch_bank.gif",
  },
  {
    id: "daily-coltzans-shrine",
    name: "Coltzan's Shrine",
    url: "https://www.neopets.com/desert/shrine.phtml",
    group: "Freebies",
    cooldown: "13h",
    notes: "Every 13 hours",
    iconUrl: "https://images.neopets.com/items/bd_desert_deathmask.gif",
  },
  {
    id: "daily-fruit-machine",
    name: "Fruit Machine",
    url: "https://www.neopets.com/desert/fruitmachine.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/food_desert3.gif",
  },
  {
    id: "daily-giant-jelly",
    name: "Giant Jelly",
    url: "https://www.neopets.com/jelly/jelly.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/jel_cornupepper_whole.gif",
  },
  {
    id: "daily-giant-omelette",
    name: "Giant Omelette",
    url: "https://www.neopets.com/prehistoric/omelette.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/om_sausage_pepperoni1.gif",
  },
  {
    id: "daily-grave-danger",
    name: "Grave Danger",
    url: "https://www.neopets.com/halloween/gravedanger/",
    group: "Freebies",
    cooldown: "7h",
    notes: "Approximately every 7 hours",
    iconUrl: "https://images.neopets.com/items/boo_zombiehandbook.gif",
  },
  {
    id: "daily-grumpy-old-king",
    name: "Grumpy Old King",
    url: "https://www.neopets.com/medieval/grumpyking.phtml",
    group: "Freebies",
    cooldown: "2/day",
    notes: "Twice a day",
    iconUrl: "https://images.neopets.com/items/toy_plushie_skarl.gif",
  },
  {
    id: "daily-healing-springs",
    name: "Healing Springs",
    url: "https://www.neopets.com/faerieland/springs.phtml",
    group: "Freebies",
    cooldown: "30m",
    notes: "Every 30 minutes",
    iconUrl: "https://images.neopets.com/items/mag_healing_striped.gif",
  },
  {
    id: "daily-money-tree",
    name: "Money Tree",
    url: "https://www.neopets.com/donations.phtml",
    group: "Freebies",
    cooldown: "10/day",
    notes: "Up to 10 claims a day",
    iconUrl: "https://images.neopets.com/items/mini_moneytree.gif",
  },
  {
    id: "daily-tombola",
    name: "Tombola",
    url: "https://www.neopets.com/island/tombola.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/toy_squeezy_tombola.gif",
  },
  {
    id: "daily-trudys-surprise",
    name: "Trudy's Surprise",
    url: "https://www.neopets.com/trudys_surprise.phtml",
    group: "Freebies",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/boo_defender_mynci.gif",
  },
  {
    id: "daily-desert-kiosk",
    name: "Desert Kiosk",
    url: "https://www.neopets.com/desert/sc/kiosk.phtml",
    group: "Scratchcards",
    cooldown: "4h",
    notes: "Every 4 hours",
    iconUrl: "https://images.neopets.com/items/scr_coltzans_cash.gif",
  },
  {
    id: "daily-haunted-kiosk",
    name: "Haunted Kiosk",
    url: "https://www.neopets.com/halloween/scratch.phtml",
    group: "Scratchcards",
    cooldown: "2h",
    notes: "Every 2 hours",
    iconUrl: "https://images.neopets.com/items/bd_sssidney_tickets.gif",
  },
  {
    id: "daily-ice-caves-kiosk",
    name: "Ice Caves Kiosk",
    url: "https://www.neopets.com/winter/kiosk.phtml",
    group: "Scratchcards",
    cooldown: "6h",
    notes: "Every 6 hours",
    iconUrl: "https://images.neopets.com/items/toy_kiosk_plushie.gif",
  },
  {
    id: "daily-food-club",
    name: "Food Club",
    url: "https://www.neopets.com/pirates/foodclub.phtml?type=bet",
    group: "Planning",
    cooldown: "daily",
    notes: "Check the daily betting round",
    iconUrl: "https://images.neopets.com/games/pages/trophies/88_1.png",
  },
  {
    id: "daily-stock-market",
    name: "Stock Market",
    url: "https://www.neopets.com/stockmarket.phtml?type=portfolio",
    group: "Planning",
    cooldown: "anytime",
    notes: "Manual tracking",
    iconUrl: "https://images.neopets.com/games/game_stocks.gif",
  },
  {
    id: "daily-faerie-caverns",
    name: "Faerie Caverns",
    url: "https://www.neopets.com/faerieland/caverns/index.phtml",
    group: "Planning",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/bg_faerie_caverns.gif",
  },
  {
    id: "daily-illusens-glade",
    name: "Illusen's Glade",
    url: "https://www.neopets.com/medieval/earthfaerie.phtml",
    group: "Quests",
    cooldown: "12h",
    notes: "Every 12 hours",
    iconUrl: "https://images.neopets.com/items/toy_faerie_illusen.gif",
  },
  {
    id: "daily-jhudoras-bluff",
    name: "Jhudora's Bluff",
    url: "https://www.neopets.com/faerieland/darkfaerie.phtml",
    group: "Quests",
    cooldown: "12h",
    notes: "Every 12 hours",
    iconUrl: "https://images.neopets.com/items/toy_faerie_jhudora.gif",
  },
  {
    id: "daily-kitchen-quests",
    name: "Kitchen Quests",
    url: "https://www.neopets.com/island/kitchen.phtml",
    group: "Quests",
    cooldown: "10/day",
    notes: "Up to 10 a day",
    iconUrl: "https://images.neopets.com/items/toy_kitchenquest_flotsam.gif",
  },
  {
    id: "daily-the-coincidence",
    name: "The Coincidence",
    url: "https://www.neopets.com/space/coincidence.phtml",
    group: "Quests",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/rpp_reu2014_robotassispetpet.gif",
  },
  {
    id: "daily-lab-ray",
    name: "Lab Ray",
    url: "https://www.neopets.com/lab.phtml",
    group: "Pet Care",
    cooldown: "daily",
    notes: "Once a day when unlocked",
    iconUrl: "https://images.neopets.com/items/labmap_09.gif",
  },
  {
    id: "daily-petpet-lab-ray",
    name: "Petpet Lab Ray",
    url: "https://www.neopets.com/petpetlab.phtml",
    group: "Pet Care",
    cooldown: "daily",
    notes: "Once a day when unlocked",
    iconUrl: "https://images.neopets.com/items/petpetlab_soot.gif",
  },
  {
    id: "daily-battledome",
    name: "Battledome",
    url: "https://www.neopets.com/dome/",
    group: "Pet Care",
    cooldown: "anytime",
    notes: "Manual tracking",
    iconUrl: "https://images.neopets.com/items/bd_spirit_blade.gif",
  },
  {
    id: "daily-wheel-excitement",
    name: "Wheel of Excitement",
    url: "https://www.neopets.com/faerieland/wheel.phtml",
    group: "Wheels",
    cooldown: "2h",
    notes: "Every 2 hours",
    iconUrl: "https://images.neopets.com/items/toy_faerie_light.gif",
  },
  {
    id: "daily-wheel-knowledge",
    name: "Wheel of Knowledge",
    url: "https://www.neopets.com/medieval/knowledge.phtml",
    group: "Wheels",
    cooldown: "daily",
    notes: "Once a day",
    iconUrl: "https://images.neopets.com/items/toy_bv_wheelofknowledge.gif",
  },
  {
    id: "daily-wheel-mediocrity",
    name: "Wheel of Mediocrity",
    url: "https://www.neopets.com/prehistoric/mediocrity.phtml",
    group: "Wheels",
    cooldown: "40m",
    notes: "Every 40 minutes",
    iconUrl: "https://images.neopets.com/items/toy_action_plesio.gif",
  },
  {
    id: "daily-wheel-misfortune",
    name: "Wheel of Misfortune",
    url: "https://www.neopets.com/halloween/wheel/index.phtml",
    group: "Wheels",
    cooldown: "2h",
    notes: "Every 2 hours",
    iconUrl: "https://images.neopets.com/items/gar_wheelmisfortune.gif",
  },
]);
